In [387]:
# Importing the libraries we are going to use
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score

In [388]:
# Defining data path and reading the dataframe
path='data/matches_laliga.csv'
matches=pd.read_csv(path,index_col=0)
matches.head(10)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2025-08-16,19:30,La Liga,Matchweek 1,Sat,Away,W,3.0,0.0,Mallorca,...,Match Report,NaN,24.0,8.0,18.9,1.0,0,0,2025,Barcelona
1,2025-08-23,21:30,La Liga,Matchweek 2,Sat,Away,W,3.0,2.0,Levante,...,Match Report,NaN,26.0,10.0,17.0,1.0,0,0,2025,Barcelona
2,2025-08-31,21:30,La Liga,Matchweek 3,Sun,Away,D,1.0,1.0,Rayo Vallecano,...,Match Report,NaN,11.0,2.0,20.3,0.0,1,1,2025,Barcelona
3,2025-09-14,21:00,La Liga,Matchweek 4,Sun,Home,W,6.0,0.0,Valencia,...,Match Report,NaN,24.0,10.0,18.4,0.0,0,0,2025,Barcelona
5,2025-09-21,21:00,La Liga,Matchweek 5,Sun,Home,W,3.0,0.0,Getafe,...,Match Report,NaN,16.0,7.0,18.2,2.0,0,0,2025,Barcelona
6,2025-09-25,21:30,La Liga,Matchweek 6,Thu,Away,W,3.0,1.0,Oviedo,...,Match Report,NaN,22.0,10.0,16.5,1.0,0,0,2025,Barcelona
7,2025-09-28,18:30,La Liga,Matchweek 7,Sun,Home,W,2.0,1.0,Real Sociedad,...,Match Report,NaN,22.0,9.0,17.5,1.0,0,0,2025,Barcelona
0,2025-08-19,21:00,La Liga,Matchweek 1,Tue,Home,W,1.0,0.0,Osasuna,...,Match Report,NaN,17.0,4.0,20.7,0.0,1,1,2025,Real Madrid
1,2025-08-24,21:30,La Liga,Matchweek 2,Sun,Away,W,3.0,0.0,Oviedo,...,Match Report,NaN,26.0,10.0,19.5,1.0,0,0,2025,Real Madrid
2,2025-08-30,21:30,La Liga,Matchweek 3,Sat,Home,W,2.0,1.0,Mallorca,...,Match Report,NaN,17.0,7.0,20.3,1.0,0,0,2025,Real Madrid

In [389]:
matches.tail(10)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
43,2020-06-16,19:30,La Liga,Matchweek 29,Tue,Away,D,0.0,0.0,Getafe,...,Match Report,NaN,5.0,3.0,15.8,0.0,0,0,2019,Espanyol
44,2020-06-20,14:00,La Liga,Matchweek 30,Sat,Home,L,1.0,3.0,Levante,...,Match Report,NaN,10.0,3.0,18.3,0.0,0,0,2019,Espanyol
45,2020-06-25,22:00,La Liga,Matchweek 31,Thu,Away,L,0.0,1.0,Betis,...,Match Report,NaN,9.0,3.0,23.2,1.0,0,0,2019,Espanyol
46,2020-06-28,22:00,La Liga,Matchweek 32,Sun,Home,L,0.0,1.0,Real Madrid,...,Match Report,NaN,8.0,5.0,20.1,2.0,0,0,2019,Espanyol
47,2020-07-02,19:30,La Liga,Matchweek 33,Thu,Away,L,1.0,2.0,Real Sociedad,...,Match Report,NaN,4.0,3.0,23.3,0.0,0,0,2019,Espanyol
48,2020-07-05,17:00,La Liga,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,...,Match Report,NaN,7.0,2.0,18.9,1.0,0,0,2019,Espanyol
49,2020-07-08,22:00,La Liga,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,...,Match Report,NaN,11.0,2.0,18.1,1.0,0,0,2019,Espanyol
50,2020-07-12,14:00,La Liga,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,...,Match Report,NaN,14.0,3.0,20.8,3.0,0,0,2019,Espanyol
51,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,...,Match Report,NaN,18.0,6.0,21.3,3.0,0,0,2019,Espanyol
52,2020-07-19,21:00,La Liga,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,...,Match Report,NaN,8.0,1.0,17.2,0.0,0,0,2019,Espanyol

In [390]:
# Checking the shape of dataframe, dropping unnecessary columns and duplicates as well as trying to understand why there are 4700 matches and their distribution across teams and rounds, it seems to be an effect of worldcup and covid which caused schedule issues. The data itself seems to be clean and not missing values.

In [391]:
matches.shape

(4700, 28)

In [392]:
6*38*20

4560

In [393]:
matches.drop(columns=['comp','notes','match report']).drop_duplicates(inplace=True)

In [394]:
matches.info()

<class 'pandas.DataFrame'>
Index: 4700 entries, 0 to 52
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4700 non-null   str
 1   time           4700 non-null   str
 2   comp           4700 non-null   str
 3   round          4700 non-null   str
 4   day            4700 non-null   str
 5   venue          4700 non-null   str
 6   result         4700 non-null   str
 7   gf             4700 non-null   float64
 8   ga             4700 non-null   float64
 9   opponent       4700 non-null   str
 10  xg             4700 non-null   float64
 11  xga            4700 non-null   float64
 12  poss           4700 non-null   float64
 13  attendance     3724 non-null   float64
 14  captain        4700 non-null   str
 15  formation      4700 non-null   str
 16  opp formation  4700 non-null   str
 17  referee        4700 non-null   str
 18  match report   4700 non-null   str
 19  notes          0 non-null      float64
 20  sh             4700 non-null   float64
 21  sot            4700 non-null   float64
 22  dist           4697 non-null   float64
 23  fk             4700 non-null   float64
 24  pk             4700 non-null   int64
 25  pkatt          4700 non-null   int64
 26  season         4700 non-null   int64
 27  team           4700 non-null   str
dtypes: float64(11), int64(3), str(14)
memory usage: 1.0 MB

In [395]:
matches['team'].value_counts()

team
Barcelona          235
Real Madrid        235
Villarreal         235
Atletico Madrid    235
Real Betis         235
Getafe             235
Sevilla            235
Athletic Club      235
Valencia           235
Osasuna            235
Celta Vigo         235
Real Sociedad      235
Alaves             197
Mallorca           197
Espanyol           159
Rayo Vallecano     159
Valladolid         152
Cadiz              152
Granada            152
Elche              121
Levante            121
Girona             121
Leganes             76
Las Palmas          76
Almeria             76
Eibar               76
Huesca              38
Oviedo               7
Name: count, dtype: int64

In [396]:
matches['round'].value_counts()

round
Matchweek 1     140
Matchweek 2     140
Matchweek 3     140
Matchweek 4     140
Matchweek 5     140
Matchweek 6     140
Matchweek 7     140
Matchweek 8     120
Matchweek 9     120
Matchweek 10    120
Matchweek 11    120
Matchweek 12    120
Matchweek 13    120
Matchweek 14    120
Matchweek 15    120
Matchweek 19    120
Matchweek 16    120
Matchweek 17    120
Matchweek 18    120
Matchweek 20    120
Matchweek 21    120
Matchweek 22    120
Matchweek 23    120
Matchweek 24    120
Matchweek 25    120
Matchweek 26    120
Matchweek 28    120
Matchweek 27    120
Matchweek 29    120
Matchweek 30    120
Matchweek 31    120
Matchweek 32    120
Matchweek 33    120
Matchweek 34    120
Matchweek 35    120
Matchweek 36    120
Matchweek 37    120
Matchweek 38    120
Name: count, dtype: int64

In [397]:
# Encoding categorical features that I will use in model.

In [398]:
matches["date"] = pd.to_datetime(matches["date"])

In [399]:
matches['venue_code']= matches['venue'].astype('category').cat.codes

In [400]:
matches['opp_code']=matches['opponent'].astype('category').cat.codes

In [401]:
matches['hour']=matches['time'].str.split(':').str[0].astype(int)

In [402]:
matches['day_code']=matches['date'].dt.dayofweek

In [403]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code
0,2025-08-16,19:30,La Liga,Matchweek 1,Sat,Away,W,3.0,0.0,Mallorca,...,18.9,1.0,0,0,2025,Barcelona,0,18,19,5
1,2025-08-23,21:30,La Liga,Matchweek 2,Sat,Away,W,3.0,2.0,Levante,...,17.0,1.0,0,0,2025,Barcelona,0,17,21,5
2,2025-08-31,21:30,La Liga,Matchweek 3,Sun,Away,D,1.0,1.0,Rayo Vallecano,...,20.3,0.0,1,1,2025,Barcelona,0,21,21,6
3,2025-09-14,21:00,La Liga,Matchweek 4,Sun,Home,W,6.0,0.0,Valencia,...,18.4,0.0,0,0,2025,Barcelona,1,25,21,6
5,2025-09-21,21:00,La Liga,Matchweek 5,Sun,Home,W,3.0,0.0,Getafe,...,18.2,2.0,0,0,2025,Barcelona,1,11,21,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,2020-07-05,17:00,La Liga,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,...,18.9,1.0,0,0,2019,Espanyol,1,16,17,6
49,2020-07-08,22:00,La Liga,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,...,18.1,1.0,0,0,2019,Espanyol,0,4,22,2
50,2020-07-12,14:00,La Liga,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,...,20.8,3.0,0,0,2019,Espanyol,1,8,14,6
51,2020-07-16,21:00,La Liga,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,...,21.3,3.0,0,0,2019,Espanyol,0,25,21,3
52,2020-07-19,21:00,La Liga,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,...,17.2,0.0,0,0,2019,Espanyol,1,6,21,6

In [404]:
matches["target"] = (matches["result"] == "W").astype("int")

In [405]:
# Defininf the model and setting parameters. Splitting data into train and test sets.

In [406]:
model= RandomForestClassifier(n_estimators=100,min_samples_split=10,random_state=11)

In [407]:
train=matches[matches['date']<'2024-01-01']
test=matches[matches['date']>='2024-01-01']

In [ ]:
# Defininf the features to be used and fitting them in model.

In [408]:
features=['venue_code','opp_code','hour','day_code']

In [409]:
model.fit(train[features],train['target'])

RandomForestClassifier(min_samples_split=10, random_state=11)

In [ ]:
# Making predictions.

In [410]:
preds=model.predict(test[features])

In [410]:
# Checking accuracy of prediction and making a confusion matrix to see false positives and true negatives.

In [411]:
acc=accuracy_score(test['target'],preds)

In [412]:
acc

0.6207692307692307

In [413]:
combined = (pd.DataFrame(dict(actual=test["target"], predicted=preds)))
combined=combined.reset_index(drop=True)

In [414]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          646  171
1          322  161

In [414]:
# While the model predicts outcome farely well for non-wins(losses and draws), the model is not good at predicting wins. This is due to the fact that our features are not good predictorsm we try to improve them later on

In [415]:
# prediction precision score
precision_score(test["target"],preds)

0.48493975903614456

In [ ]:
# grouping teams to calculate rolling averages of features to improve prediction.

In [416]:
matches_teamwise=matches.groupby('team')

In [417]:
group=matches_teamwise.get_group('Barcelona').head(10)

In [418]:
def rolling_averages(group,cols,new):
    group=group.sort_values('date')
    roll_stats=group[cols].rolling(3,closed='left').mean()
    group[new]=roll_stats
    group=group.dropna(subset=new)
    return group

In [ ]:
# defining features that will require rolling averages.

In [419]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2025-08-16,19:30,La Liga,Matchweek 1,Sat,Away,W,3.0,0.0,Mallorca,...,5,1,2.000000,1.000000,17.333333,5.000000,18.166667,0.666667,0.333333,0.333333
1,2025-08-23,21:30,La Liga,Matchweek 2,Sat,Away,W,3.0,2.0,Levante,...,5,1,2.333333,0.666667,19.666667,6.000000,18.266667,0.666667,0.000000,0.000000
2,2025-08-31,21:30,La Liga,Matchweek 3,Sun,Away,D,1.0,1.0,Rayo Vallecano,...,6,0,2.666667,1.000000,24.000000,7.666667,18.400000,1.000000,0.000000,0.000000
3,2025-09-14,21:00,La Liga,Matchweek 4,Sun,Home,W,6.0,0.0,Valencia,...,6,1,2.333333,1.000000,20.333333,6.666667,18.733333,0.666667,0.333333,0.333333
5,2025-09-21,21:00,La Liga,Matchweek 5,Sun,Home,W,3.0,0.0,Getafe,...,6,1,3.333333,1.000000,20.333333,7.333333,18.566667,0.333333,0.333333,0.333333
6,2025-09-25,21:30,La Liga,Matchweek 6,Thu,Away,W,3.0,1.0,Oviedo,...,3,1,3.333333,0.333333,17.000000,6.333333,18.966667,0.666667,0.333333,0.333333
7,2025-09-28,18:30,La Liga,Matchweek 7,Sun,Home,W,2.0,1.0,Real Sociedad,...,6,1,4.000000,0.333333,20.666667,9.000000,17.700000,1.000000,0.000000,0.000000

In [420]:
matches_roll=matches.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols))

In [421]:
matches_roll.droplevel('team').reset_index()

,index,date,time,comp,round,day,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,3,2019-09-15,14:00,La Liga,Matchweek 4,Sun,Home,L,0.0,1.0,...,6,0,0.666667,0.333333,8.000000,1.666667,15.100000,0.333333,0.000000,0.000000
1,4,2019-09-22,18:30,La Liga,Matchweek 5,Sun,Away,L,0.0,2.0,...,6,0,0.333333,0.666667,7.333333,1.000000,14.733333,0.000000,0.000000,0.000000
2,5,2019-09-26,21:00,La Liga,Matchweek 6,Thu,Away,L,0.0,3.0,...,3,0,0.333333,1.333333,5.333333,0.666667,15.433333,0.000000,0.000000,0.000000
3,6,2019-09-29,16:00,La Liga,Matchweek 7,Sun,Home,W,2.0,0.0,...,6,1,0.000000,2.000000,5.333333,0.333333,16.900000,0.000000,0.000000,0.000000
4,7,2019-10-05,18:30,La Liga,Matchweek 8,Sat,Away,L,1.0,2.0,...,5,0,0.666667,1.666667,6.333333,2.000000,18.700000,0.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4602,2,2025-08-31,17:00,La Liga,Matchweek 3,Sun,Away,D,1.0,1.0,...,6,0,3.666667,0.666667,18.666667,8.000000,15.533333,0.000000,0.000000,0.000000
4603,3,2025-09-13,21:00,La Liga,Matchweek 4,Sat,Away,L,0.0,2.0,...,5,0,2.666667,0.333333,17.333333,6.666667,15.966667,0.000000,0.000000,0.000000
4604,5,2025-09-20,18:30,La Liga,Matchweek 5,Sat,Home,W,2.0,1.0,...,5,1,2.000000,1.000000,11.666667,3.666667,16.733333,0.333333,0.000000,0.000000
4605,6,2025-09-23,21:30,La Liga,Matchweek 6,Tue,Away,W,2.0,1.0,...,1,1,1.000000,1.333333,14.000000,4.000000,17.500000,0.333333,0.000000,0.000000
4606,7,2025-09-27,21:00,La Liga,Matchweek 7,Sat,Home,W,1.0,0.0,...,5,1,1.333333,1.333333,15.333333,4.666667,17.033333,0.333333,0.000000,0.000000

In [422]:
# defining the function to predict outcome using rolling averages of features as a feature in model as well.
def predict_outcome(data, predictors):
    model = RandomForestClassifier(n_estimators=100, min_samples_split=10, random_state=11)
    train = data[data["date"] < '2024-01-01']
    test = data[data["date"] >= '2024-01-01']
    model.fit(train[predictors], train["target"])
    preds = model.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [423]:
combined,precision=predict_outcome(matches_roll,features + new_cols)

In [424]:
precision

0.5508771929824562

In [ ]:
#The prediction score has shown an increment by 0.07, which is a good improvement.